#!/usr/bin/env python3
"""T-53 lote 1 — mechanical port of the U-13 catalogs from the Blazor app.

Reads `K.cs`, `StringsPtBr.cs` and `StringsEn.cs` from the entrelares-app
repo and regenerates the Dart catalogs in `packages/entrelares_core`.
The Dart files are committed; re-run this only to re-sync after the C#
catalogs change (the Blazor freeze makes that unlikely, but the tool is
the record of HOW the port was made — no hand-transcription).

Usage:
    python tool/port_catalogs.py [path-to-entrelares-app]
"""
import re
import sys
from pathlib import Path

FLUTTER_ROOT = Path(__file__).resolve().parent.parent
# Default assumes the sibling checkout layout (…/repos/entrelares-flutter and
# …/repos/entrelares-app); pass the path explicitly from a worktree.
APP_REPO = Path(sys.argv[1]) if len(sys.argv) > 1 else FLUTTER_ROOT.parent / "entrelares-app"
SRC = APP_REPO / "Entrelares" / "Localization"
OUT = FLUTTER_ROOT / "packages" / "entrelares_core" / "lib" / "src" / "localization"

CONST_RE = re.compile(r'^\s*public const string (\w+) = "((?:[^"\\]|\\.)*)";')
ENTRY_RE = re.compile(r'^\s*\[K\.(\w+)\] = "((?:[^"\\]|\\.)*)",')
SECTION_RE = re.compile(r'^\s*// ── (.*?) ─+')


def camel(name: str) -> str:
    return name[0].lower() + name[1:]


def cs_unescape(s: str) -> str:
    # Only \" and \\ occur in these catalogs; fail loudly on anything else.
    out, i = [], 0
    while i < len(s):
        if s[i] == "\\":
            nxt = s[i + 1]
            if nxt not in '"\\':
                raise SystemExit(f"unsupported C# escape \\{nxt} in: {s}")
            out.append(nxt)
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def dart_quote(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("$", "\\$").replace("'", "\\'") + "'"


def parse(path: Path, line_re):
    """Yields ('section', title) and ('entry', name, value) in file order."""
    for line in path.read_text(encoding="utf-8").splitlines():
        m = SECTION_RE.match(line)
        if m:
            yield ("section", m.group(1).strip())
            continue
        m = line_re.match(line)
        if m:
            yield ("entry", m.group(1), cs_unescape(m.group(2)))


HEADER = """\
// GENERATED by tool/port_catalogs.py from the entrelares-app repo
// (Entrelares/Localization/{src}) — do NOT hand-edit. Re-run the tool
// to re-sync. U-13: {what}
"""


def gen_k(items) -> str:
    lines = [HEADER.format(src="K.cs", what="every localizable string key, as compile-time constants.")]
    lines.append("/// A typo in `K.loginSubmitt` fails to compile; a bare string key would")
    lines.append("/// render itself in front of a user. Key parity with both catalogs is a")
    lines.append("/// `dart test` gate (localization_test.dart).")
    lines.append("abstract final class K {")
    first = True
    for item in items:
        if item[0] == "section":
            if not first:
                lines.append("")
            lines.append(f"  // ── {item[1]} ──")
        else:
            lines.append(f"  static const String {camel(item[1])} = {dart_quote(item[2])};")
        first = False
    lines.append("")
    lines.append("  /// Every declared key, in declaration order — the Dart stand-in for the")
    lines.append("  /// C# reflection scan in `LocalizationTests.DeclaredKeys()`. The parity")
    lines.append("  /// tests iterate this list; the generator keeps it complete by construction.")
    lines.append("  static const List<String> allKeys = [")
    for item in items:
        if item[0] == "entry":
            lines.append(f"    {camel(item[1])},")
    lines.append("  ];")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_strings(items, cls: str, src: str, what: str) -> str:
    lines = [HEADER.format(src=src, what=what)]
    lines.append("import 'k.dart';")
    lines.append("")
    lines.append(f"abstract final class {cls} {{")
    lines.append("  static const Map<String, String> values = {")
    for item in items:
        if item[0] == "section":
            lines.append(f"    // ── {item[1]} ──")
        else:
            lines.append(f"    K.{camel(item[1])}: {dart_quote(item[2])},")
    lines.append("  };")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    k_items = list(parse(SRC / "K.cs", CONST_RE))
    pt_items = list(parse(SRC / "StringsPtBr.cs", ENTRY_RE))
    en_items = list(parse(SRC / "StringsEn.cs", ENTRY_RE))

    n = lambda items: sum(1 for i in items if i[0] == "entry")
    print(f"K: {n(k_items)}  PtBr: {n(pt_items)}  En: {n(en_items)}")
    if not (n(k_items) == n(pt_items) == n(en_items)):
        raise SystemExit("catalog counts differ — refusing to generate")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "k.dart").write_text(gen_k(k_items), encoding="utf-8", newline="\n")
    (OUT / "strings_pt_br.dart").write_text(
        gen_strings(pt_items, "StringsPtBr", "StringsPtBr.cs",
                    "the PT-BR catalog — the ORIGINAL product text, verbatim."),
        encoding="utf-8", newline="\n")
    (OUT / "strings_en.dart").write_text(
        gen_strings(en_items, "StringsEn", "StringsEn.cs",
                    "the EN catalog. Placeholder SETS match PT-BR; order may differ."),
        encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
