-- =============================================================================
-- V001 — Initial schema
-- Guarda Compartilhada — Supabase/PostgreSQL
--
-- Creates all tables, the audit trigger, row-level security policies,
-- and role grants required to run the application from scratch.
-- Run once against a fresh Supabase project in the SQL Editor.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- EXTENSIONS (Supabase enables these by default; included for completeness)
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto"   WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"  WITH SCHEMA extensions;


-- ---------------------------------------------------------------------------
-- TABLES
-- ---------------------------------------------------------------------------

-- Custody roles (e.g. "father", "mother")
CREATE TABLE IF NOT EXISTS public.roles (
	id      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	role    text   NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);

-- One row per app user, linked to Supabase Auth
CREATE TABLE IF NOT EXISTS public.profiles (
	id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_id    uuid                     NOT NULL,
	full_name  text                     NOT NULL,
	role_id    bigint                   NOT NULL,
	email      text                     NOT NULL,
	created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	CONSTRAINT profiles_pkey         PRIMARY KEY (id),
	CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id)  REFERENCES auth.users (id),
	CONSTRAINT profiles_role_id_fkey FOREIGN KEY (role_id)  REFERENCES public.roles (id)
);

-- One row per calendar date (schedule_date is unique — only one entry per day)
CREATE TABLE IF NOT EXISTS public.care_schedules (
	id                   bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	schedule_date        date                     NOT NULL,
	scheduled_parent_id  bigint                   NOT NULL,
	actual_parent_id     bigint,
	notes                text,
	handoff_time         time without time zone,
	created_at           timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	updated_at           timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	CONSTRAINT care_schedules_pkey                     PRIMARY KEY (id),
	CONSTRAINT care_schedules_schedule_date_key        UNIQUE (schedule_date),
	CONSTRAINT care_schedules_scheduled_parent_id_fkey FOREIGN KEY (scheduled_parent_id) REFERENCES public.profiles (id),
	CONSTRAINT care_schedules_actual_parent_id_fkey    FOREIGN KEY (actual_parent_id)    REFERENCES public.profiles (id)
);

-- Append-only audit log — populated exclusively by the trigger below
CREATE TABLE IF NOT EXISTS public.activity_logs (
	id               bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	schedule_id      bigint,
	affected_date    date                     NOT NULL,
	action           text                     NOT NULL,
	old_data         jsonb,
	new_data         jsonb,
	performed_by_id  bigint,
	created_at       timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	CONSTRAINT activity_logs_pkey                 PRIMARY KEY (id),
	CONSTRAINT activity_logs_schedule_id_fkey     FOREIGN KEY (schedule_id)     REFERENCES public.care_schedules (id) ON DELETE SET NULL,
	CONSTRAINT activity_logs_performed_by_id_fkey FOREIGN KEY (performed_by_id) REFERENCES public.profiles (id)
);


-- ---------------------------------------------------------------------------
-- AUDIT TRIGGER
-- Fires after INSERT / UPDATE / DELETE on care_schedules.
-- SECURITY DEFINER allows the function to write to activity_logs
-- even though clients have no direct write access to that table.
-- performed_by_id is resolved from the current Supabase Auth session.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.audit_care_schedule_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
	INSERT INTO public.activity_logs (
		schedule_id,
		affected_date,
		action,
		old_data,
		new_data,
		performed_by_id
	) VALUES (
		-- On DELETE, schedule_id would violate the FK, so store NULL
		CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE NEW.id END,
		COALESCE(NEW.schedule_date, OLD.schedule_date),
		TG_OP,
		CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
		CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END,
		(SELECT id FROM public.profiles WHERE user_id = auth.uid())
	);

	IF TG_OP = 'DELETE' THEN
		RETURN OLD;
	END IF;
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_audit_care_schedule
	AFTER INSERT OR UPDATE OR DELETE ON public.care_schedules
	FOR EACH ROW EXECUTE FUNCTION public.audit_care_schedule_changes();


-- ---------------------------------------------------------------------------
-- ROW-LEVEL SECURITY
-- ---------------------------------------------------------------------------

ALTER TABLE public.roles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.care_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs  ENABLE ROW LEVEL SECURITY;

-- roles: read-only for any authenticated user
CREATE POLICY "roles_authenticated_read"
	ON public.roles FOR SELECT TO authenticated USING (true);

-- profiles: any authenticated user can read all profiles
CREATE POLICY "profiles_authenticated_read"
	ON public.profiles FOR SELECT TO authenticated USING (true);

-- profiles: a user can only insert their own profile
CREATE POLICY "profiles_own_insert"
	ON public.profiles FOR INSERT TO authenticated
	WITH CHECK (user_id = auth.uid());

-- profiles: a user can only update their own profile
CREATE POLICY "profiles_own_update"
	ON public.profiles FOR UPDATE TO authenticated
	USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- care_schedules: authenticated users have full access (all operations)
CREATE POLICY "care_schedules_authenticated_select"
	ON public.care_schedules FOR SELECT TO authenticated USING (true);

CREATE POLICY "care_schedules_authenticated_insert"
	ON public.care_schedules FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "care_schedules_authenticated_update"
	ON public.care_schedules FOR UPDATE TO authenticated
	USING (true) WITH CHECK (true);

CREATE POLICY "care_schedules_authenticated_delete"
	ON public.care_schedules FOR DELETE TO authenticated USING (true);

-- activity_logs: authenticated users can read; writes come only from the
-- SECURITY DEFINER trigger — no client write policy is defined intentionally
CREATE POLICY "activity_logs_authenticated_read"
	ON public.activity_logs FOR SELECT TO authenticated USING (true);


-- ---------------------------------------------------------------------------
-- GRANTS
-- ---------------------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

GRANT ALL ON public.roles          TO anon, authenticated, service_role;
GRANT ALL ON public.profiles       TO anon, authenticated, service_role;
GRANT ALL ON public.care_schedules TO anon, authenticated, service_role;
GRANT ALL ON public.activity_logs  TO anon, authenticated, service_role;

GRANT ALL ON SEQUENCE public.roles_id_seq          TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.profiles_id_seq       TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.care_schedules_id_seq TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.activity_logs_id_seq  TO anon, authenticated, service_role;

GRANT ALL ON FUNCTION public.audit_care_schedule_changes() TO anon, authenticated, service_role;


-- ---------------------------------------------------------------------------
-- SEED DATA (optional — run manually for initial role setup)
-- ---------------------------------------------------------------------------

-- INSERT INTO public.roles (role) VALUES ('father'), ('mother');
