-- =============================================================================
-- V002 — Swap request workflow
-- Guarda Compartilhada — Supabase/PostgreSQL
--
-- Adds the swap_requests and notifications tables required for the two-party
-- custody-day approval workflow.
-- Apply via the Supabase SQL Editor against the target project AFTER V001.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- swap_requests
-- One row per pending/resolved day-swap request.
-- A partial unique index prevents more than one pending request per day.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.swap_requests (
	id                         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	schedule_date              date                     NOT NULL,
	schedule_id                bigint,
	requesting_profile_id      bigint                   NOT NULL,
	target_profile_id          bigint                   NOT NULL,
	previous_actual_parent_id  bigint,
	proposed_actual_parent_id  bigint                   NOT NULL,
	proposed_handoff_time      time without time zone,
	status                     text                     NOT NULL DEFAULT 'pending'
								   CONSTRAINT swap_requests_status_check
								   CHECK (status IN ('pending','approved','rejected','cancelled','reverted')),
	rejection_reason           text,
	created_at                 timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	updated_at                 timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	resolved_at                timestamp with time zone,
	CONSTRAINT swap_requests_pkey                             PRIMARY KEY (id),
	CONSTRAINT swap_requests_schedule_id_fkey                 FOREIGN KEY (schedule_id)               REFERENCES public.care_schedules (id) ON DELETE SET NULL,
	CONSTRAINT swap_requests_requesting_profile_id_fkey       FOREIGN KEY (requesting_profile_id)     REFERENCES public.profiles (id),
	CONSTRAINT swap_requests_target_profile_id_fkey           FOREIGN KEY (target_profile_id)         REFERENCES public.profiles (id),
	CONSTRAINT swap_requests_previous_actual_parent_id_fkey   FOREIGN KEY (previous_actual_parent_id) REFERENCES public.profiles (id),
	CONSTRAINT swap_requests_proposed_actual_parent_id_fkey   FOREIGN KEY (proposed_actual_parent_id) REFERENCES public.profiles (id)
);

-- Only one pending request is allowed per calendar day.
-- Approved/rejected/cancelled/reverted requests are kept for history.
CREATE UNIQUE INDEX IF NOT EXISTS swap_requests_one_pending_per_date
	ON public.swap_requests (schedule_date)
	WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- notifications
-- In-app notification feed. Written by the C# service layer; read by the
-- authenticated user who owns the row. Supabase Realtime must be enabled on
-- this table in each project (Database → Replication → supabase_realtime).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.notifications (
	id                  bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	recipient_profile_id bigint                  NOT NULL,
	type                text                     NOT NULL,
	title               text                     NOT NULL,
	message             text                     NOT NULL,
	swap_request_id     bigint,
	is_read             boolean                  NOT NULL DEFAULT false,
	created_at          timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	CONSTRAINT notifications_pkey                   PRIMARY KEY (id),
	CONSTRAINT notifications_recipient_fkey         FOREIGN KEY (recipient_profile_id) REFERENCES public.profiles (id),
	CONSTRAINT notifications_swap_request_id_fkey   FOREIGN KEY (swap_request_id)      REFERENCES public.swap_requests (id) ON DELETE SET NULL
);


-- ---------------------------------------------------------------------------
-- ROW-LEVEL SECURITY
-- ---------------------------------------------------------------------------

ALTER TABLE public.swap_requests  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications   ENABLE ROW LEVEL SECURITY;

-- swap_requests: a user can read any request they are the requester or target of
CREATE POLICY "swap_requests_select_own"
	ON public.swap_requests FOR SELECT TO authenticated
	USING (
		requesting_profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
		OR
		target_profile_id     = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
	);

-- swap_requests: any authenticated user can create a request
CREATE POLICY "swap_requests_insert"
	ON public.swap_requests FOR INSERT TO authenticated
	WITH CHECK (true);

-- swap_requests: requester can cancel (status → cancelled) or mark reverted;
--               target can approve or reject (status → approved / rejected).
--               Both are permitted via the same UPDATE policy — enforcement of
--               which transitions are valid is the responsibility of the
--               C# service layer.
CREATE POLICY "swap_requests_update_parties"
	ON public.swap_requests FOR UPDATE TO authenticated
	USING (
		requesting_profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
		OR
		target_profile_id     = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
	)
	WITH CHECK (true);

-- notifications: a user can only read their own notifications
CREATE POLICY "notifications_select_own"
	ON public.notifications FOR SELECT TO authenticated
	USING (
		recipient_profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
	);

-- notifications: any authenticated user can insert (the C# service layer
--               inserts on behalf of both parties after validating the request)
CREATE POLICY "notifications_insert"
	ON public.notifications FOR INSERT TO authenticated
	WITH CHECK (true);

-- notifications: a user can only update their own notification (e.g. is_read)
CREATE POLICY "notifications_update_own"
	ON public.notifications FOR UPDATE TO authenticated
	USING (
		recipient_profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
	)
	WITH CHECK (
		recipient_profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
	);


-- ---------------------------------------------------------------------------
-- GRANTS
-- ---------------------------------------------------------------------------

GRANT ALL ON public.swap_requests  TO anon, authenticated, service_role;
GRANT ALL ON public.notifications   TO anon, authenticated, service_role;

GRANT ALL ON SEQUENCE public.swap_requests_id_seq  TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.notifications_id_seq   TO anon, authenticated, service_role;
