-- =============================================================================
-- V008 — Families, family-scoped RLS and admin authorization (F-14 + S-06)
-- Guarda Compartilhada — Supabase/PostgreSQL
--
-- Introduces the multi-tenancy backbone and the admin role:
--
-- 1. families table; family_id on profiles / care_schedules / swap_requests /
--    activity_logs; profiles.is_admin. Backfills everything into family #1 and
--    promotes the project owner's profile to admin (fallback: oldest profile).
-- 2. Uniqueness becomes per-family: care_schedules UNIQUE (family_id,
--    schedule_date); the one-pending-per-date partial index gains family_id.
-- 3. family_id is auto-filled by BEFORE INSERT triggers (derived from the row's
--    parent/requester profile — spoof-proof, no client change) and immutable.
-- 4. get_my_family_id() SECURITY DEFINER helper (avoids RLS self-recursion on
--    profiles) + family-scoped RLS on profiles, care_schedules, activity_logs,
--    families; hardened INSERT policies on swap_requests and notifications.
-- 5. Profile-protection trigger: is_admin can only be changed by an admin of
--    the same family (blocks self-promotion via the own-update policy);
--    family_id is immutable; the LAST admin of a family cannot be demoted or
--    deleted (invariant: every family has at least one admin).
-- 6. Day-protection trigger on care_schedules — moves the F-12/F-13 rules into
--    the database, with an admin bypass (F-14) and a system bypass (F-24):
--       · past days are immutable                        (admin may bypass)
--       · frozen days (pending/revert_pending) locked    (admin may bypass;
--         the pending request's TARGET is exempt so approvals keep working)
--       · a day with an approved swap cannot be deleted  (admin may bypass)
--       · actual_parent changes that create or undo a swap MUST go through the
--         approval workflow — enforced for admins too (only the pending
--         request's target, applying an approval, and service_role may write
--         such a change). Closes the S-05 leftover: until now any
--         authenticated user could PATCH actual_parent_id directly.
--
-- Timezone: "today" uses America/Sao_Paulo, consistent with F-24.
-- Apply via the Supabase SQL Editor against the target project AFTER V007.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. families table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.families (
	id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name       text                     NOT NULL,
	created_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	CONSTRAINT families_pkey PRIMARY KEY (id)
);

ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.families FROM anon;
GRANT  ALL ON public.families TO authenticated, service_role;
REVOKE ALL ON SEQUENCE public.families_id_seq FROM anon;
GRANT  ALL ON SEQUENCE public.families_id_seq TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 2. New columns
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles
	ADD COLUMN IF NOT EXISTS family_id bigint REFERENCES public.families (id),
	ADD COLUMN IF NOT EXISTS is_admin  boolean NOT NULL DEFAULT false;

ALTER TABLE public.care_schedules
	ADD COLUMN IF NOT EXISTS family_id bigint REFERENCES public.families (id);

ALTER TABLE public.swap_requests
	ADD COLUMN IF NOT EXISTS family_id bigint REFERENCES public.families (id);

ALTER TABLE public.activity_logs
	ADD COLUMN IF NOT EXISTS family_id bigint REFERENCES public.families (id);

-- ---------------------------------------------------------------------------
-- 3. Backfill: everything that exists today belongs to family #1
-- ---------------------------------------------------------------------------

DO $$
DECLARE
	fam bigint;
BEGIN
	-- Idempotency: reuse the family if this migration already created it.
	SELECT id INTO fam FROM public.families ORDER BY id LIMIT 1;
	IF fam IS NULL THEN
		INSERT INTO public.families (name) VALUES ('Família Principal') RETURNING id INTO fam;
	END IF;

	UPDATE public.profiles       SET family_id = fam WHERE family_id IS NULL;
	UPDATE public.care_schedules SET family_id = fam WHERE family_id IS NULL;
	UPDATE public.swap_requests  SET family_id = fam WHERE family_id IS NULL;
	UPDATE public.activity_logs  SET family_id = fam WHERE family_id IS NULL;

	-- Initial admin: the project owner's profile (decision recorded in F-14).
	UPDATE public.profiles SET is_admin = true WHERE email = 'irineus@gmail.com';

	-- Safety net for any environment where that e-mail does not exist: every
	-- family must have at least one admin, so promote the oldest profile.
	IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE family_id = fam AND is_admin) THEN
		UPDATE public.profiles SET is_admin = true
		WHERE id = (SELECT min(id) FROM public.profiles WHERE family_id = fam);
	END IF;
END $$;

ALTER TABLE public.profiles       ALTER COLUMN family_id SET NOT NULL;
ALTER TABLE public.care_schedules ALTER COLUMN family_id SET NOT NULL;
ALTER TABLE public.swap_requests  ALTER COLUMN family_id SET NOT NULL;

-- ---------------------------------------------------------------------------
-- 4. Per-family uniqueness
-- ---------------------------------------------------------------------------

ALTER TABLE public.care_schedules
	DROP CONSTRAINT IF EXISTS care_schedules_schedule_date_key;
ALTER TABLE public.care_schedules
	ADD CONSTRAINT care_schedules_family_schedule_date_key UNIQUE (family_id, schedule_date);

DROP INDEX IF EXISTS public.swap_requests_one_pending_per_date;
CREATE UNIQUE INDEX swap_requests_one_pending_per_date
	ON public.swap_requests (family_id, schedule_date)
	WHERE status IN ('pending', 'revert_pending');

-- ---------------------------------------------------------------------------
-- 5. Helper functions (SECURITY DEFINER avoids RLS self-recursion on profiles)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_my_family_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
	SELECT family_id FROM public.profiles WHERE user_id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.get_my_family_id() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_my_family_id() TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. family_id auto-fill triggers (spoof-proof, immutable after insert)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_care_schedule_family()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		NEW.family_id := (SELECT family_id FROM public.profiles WHERE id = NEW.scheduled_parent_id);
	ELSE
		NEW.family_id := OLD.family_id;
	END IF;
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_a_set_care_schedule_family
	BEFORE INSERT OR UPDATE ON public.care_schedules
	FOR EACH ROW EXECUTE FUNCTION public.set_care_schedule_family();

CREATE OR REPLACE FUNCTION public.set_swap_request_family()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		NEW.family_id := (SELECT family_id FROM public.profiles WHERE id = NEW.requesting_profile_id);
	ELSE
		NEW.family_id := OLD.family_id;
	END IF;
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_a_set_swap_request_family
	BEFORE INSERT OR UPDATE ON public.swap_requests
	FOR EACH ROW EXECUTE FUNCTION public.set_swap_request_family();

-- Audit trigger now also records the family (needed because schedule_id is
-- nullified on DELETE — family_id keeps the log scoped forever).
CREATE OR REPLACE FUNCTION public.audit_care_schedule_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
	INSERT INTO public.activity_logs (
		schedule_id,
		affected_date,
		action,
		old_data,
		new_data,
		performed_by_id,
		family_id
	) VALUES (
		CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE NEW.id END,
		COALESCE(NEW.schedule_date, OLD.schedule_date),
		TG_OP,
		CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
		CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END,
		(SELECT id FROM public.profiles WHERE user_id = auth.uid()),
		COALESCE(NEW.family_id, OLD.family_id)
	);

	IF TG_OP = 'DELETE' THEN
		RETURN OLD;
	END IF;
	RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 7. Family-scoped RLS
-- ---------------------------------------------------------------------------

-- families: members read their own family; no client writes.
DROP POLICY IF EXISTS "families_member_read" ON public.families;
CREATE POLICY "families_member_read"
	ON public.families FOR SELECT TO authenticated
	USING (id = public.get_my_family_id());

-- profiles: read own family only (own row always readable, even mid-onboarding).
DROP POLICY IF EXISTS "profiles_authenticated_read" ON public.profiles;
CREATE POLICY "profiles_family_read"
	ON public.profiles FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id() OR user_id = auth.uid());

-- care_schedules: full access within the own family only (S-06).
DROP POLICY IF EXISTS "care_schedules_authenticated_select" ON public.care_schedules;
DROP POLICY IF EXISTS "care_schedules_authenticated_insert" ON public.care_schedules;
DROP POLICY IF EXISTS "care_schedules_authenticated_update" ON public.care_schedules;
DROP POLICY IF EXISTS "care_schedules_authenticated_delete" ON public.care_schedules;

CREATE POLICY "care_schedules_family_select"
	ON public.care_schedules FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

CREATE POLICY "care_schedules_family_insert"
	ON public.care_schedules FOR INSERT TO authenticated
	WITH CHECK ((SELECT family_id FROM public.profiles WHERE id = scheduled_parent_id) = public.get_my_family_id());

CREATE POLICY "care_schedules_family_update"
	ON public.care_schedules FOR UPDATE TO authenticated
	USING (family_id = public.get_my_family_id())
	WITH CHECK (family_id = public.get_my_family_id());

CREATE POLICY "care_schedules_family_delete"
	ON public.care_schedules FOR DELETE TO authenticated
	USING (family_id = public.get_my_family_id());

-- activity_logs: read own family's audit trail only.
DROP POLICY IF EXISTS "activity_logs_authenticated_read" ON public.activity_logs;
CREATE POLICY "activity_logs_family_read"
	ON public.activity_logs FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

-- swap_requests: INSERT hardened — requester must be the caller and the target
-- must belong to the same family (SELECT/UPDATE stay person-scoped from V004).
DROP POLICY IF EXISTS "swap_requests_insert" ON public.swap_requests;
CREATE POLICY "swap_requests_insert"
	ON public.swap_requests FOR INSERT TO authenticated
	WITH CHECK (
		requesting_profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid())
		AND (SELECT family_id FROM public.profiles WHERE id = target_profile_id) = public.get_my_family_id()
	);

-- notifications: INSERT hardened — recipient must belong to the caller's family.
DROP POLICY IF EXISTS "notifications_insert" ON public.notifications;
CREATE POLICY "notifications_insert"
	ON public.notifications FOR INSERT TO authenticated
	WITH CHECK (
		(SELECT family_id FROM public.profiles WHERE id = recipient_profile_id) = public.get_my_family_id()
	);

-- ---------------------------------------------------------------------------
-- 8. Profile protection: admin flag management + last-admin invariant
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.enforce_profile_protection()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
	actor_admin  boolean;
	actor_family bigint;
BEGIN
	-- System context (service_role / migrations): unrestricted.
	IF auth.uid() IS NULL THEN
		RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
	END IF;

	SELECT is_admin, family_id INTO actor_admin, actor_family
	FROM public.profiles WHERE user_id = auth.uid();

	IF TG_OP = 'UPDATE' THEN
		IF NEW.family_id IS DISTINCT FROM OLD.family_id THEN
			RAISE EXCEPTION 'A família de um perfil não pode ser alterada.'
				USING ERRCODE = 'check_violation';
		END IF;

		IF NEW.is_admin IS DISTINCT FROM OLD.is_admin THEN
			-- Blocks self-promotion through the profiles_own_update policy.
			IF COALESCE(actor_admin, false) = false OR actor_family IS DISTINCT FROM OLD.family_id THEN
				RAISE EXCEPTION 'Somente administradores da família podem alterar permissões de administrador.'
					USING ERRCODE = 'check_violation';
			END IF;

			-- Demotion: keep the >= 1 admin per family invariant.
			IF OLD.is_admin AND NOT NEW.is_admin AND NOT EXISTS (
				SELECT 1 FROM public.profiles
				WHERE family_id = OLD.family_id AND is_admin AND id <> OLD.id
			) THEN
				RAISE EXCEPTION 'A família precisa de pelo menos uma pessoa administradora.'
					USING ERRCODE = 'check_violation';
			END IF;
		END IF;

		RETURN NEW;
	END IF;

	-- DELETE: never remove the last admin of a family.
	IF OLD.is_admin AND NOT EXISTS (
		SELECT 1 FROM public.profiles
		WHERE family_id = OLD.family_id AND is_admin AND id <> OLD.id
	) THEN
		RAISE EXCEPTION 'A família precisa de pelo menos uma pessoa administradora.'
			USING ERRCODE = 'check_violation';
	END IF;
	RETURN OLD;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_enforce_profile_protection
	BEFORE UPDATE OR DELETE ON public.profiles
	FOR EACH ROW EXECUTE FUNCTION public.enforce_profile_protection();

-- ---------------------------------------------------------------------------
-- 9. Day protection: F-12/F-13 rules at database level with admin bypass (F-14)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.enforce_day_protection()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
	cur_profile_id bigint;
	cur_is_admin   boolean := false;
	today          date;
	the_date       date;
	fam            bigint;
	is_frozen      boolean := false;
	is_target      boolean := false;
BEGIN
	-- System context (service_role: F-24 auto-approval, migrations): unrestricted.
	SELECT id, is_admin INTO cur_profile_id, cur_is_admin
	FROM public.profiles WHERE user_id = auth.uid();
	IF cur_profile_id IS NULL THEN
		RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
	END IF;

	today    := (now() AT TIME ZONE 'America/Sao_Paulo')::date;
	the_date := COALESCE(NEW.schedule_date, OLD.schedule_date);
	fam      := COALESCE(NEW.family_id, OLD.family_id,
	                     (SELECT family_id FROM public.profiles WHERE id = NEW.scheduled_parent_id));

	SELECT bool_or(true), bool_or(target_profile_id = cur_profile_id)
	INTO is_frozen, is_target
	FROM public.swap_requests
	WHERE family_id = fam AND schedule_date = the_date
	  AND status IN ('pending', 'revert_pending');
	is_frozen := COALESCE(is_frozen, false);
	is_target := COALESCE(is_target, false);

	-- F-12: frozen days are untouchable, except by the pending request's target
	-- (who legitimately applies the calendar change while approving) or an admin.
	IF TG_OP IN ('UPDATE', 'DELETE') AND is_frozen AND NOT is_target AND NOT cur_is_admin THEN
		RAISE EXCEPTION 'Este dia tem uma solicitação pendente e não pode ser alterado.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- F-13: past days are immutable (the target exemption keeps overdue
	-- workflow completions working; admins may bypass — F-14).
	IF the_date < today AND NOT cur_is_admin AND NOT is_target THEN
		RAISE EXCEPTION 'Dias passados não podem ser alterados.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF TG_OP = 'DELETE' THEN
		-- F-12: a day with an approved swap cannot be deleted (admin may — F-14).
		IF OLD.actual_parent_id IS NOT NULL AND OLD.actual_parent_id <> OLD.scheduled_parent_id
		   AND NOT cur_is_admin AND NOT is_target THEN
			RAISE EXCEPTION 'Dias com troca aprovada não podem ser apagados.'
				USING ERRCODE = 'check_violation';
		END IF;
		RETURN OLD;
	END IF;

	-- Swap-workflow enforcement (applies to admins too — F-14 decision):
	-- creating or undoing a swap directly is forbidden; only the pending
	-- request's target (applying an approval) may write such a change.
	-- Exception: admins may correct the actual parent of PAST days (historical
	-- fixes — the workflow cannot exist for past dates), never future ones.
	IF cur_is_admin AND the_date < today THEN
		RETURN NEW;
	END IF;

	IF TG_OP = 'INSERT' THEN
		IF NEW.actual_parent_id IS NOT NULL AND NEW.actual_parent_id <> NEW.scheduled_parent_id THEN
			RAISE EXCEPTION 'Alterações do responsável real devem passar pelo fluxo de aprovação.'
				USING ERRCODE = 'check_violation';
		END IF;
	ELSIF NEW.actual_parent_id IS DISTINCT FROM OLD.actual_parent_id AND NOT is_target THEN
		IF (OLD.actual_parent_id IS NOT NULL AND OLD.actual_parent_id <> OLD.scheduled_parent_id)  -- undo/alter an approved swap
		   OR (NEW.actual_parent_id IS NOT NULL AND NEW.actual_parent_id <> NEW.scheduled_parent_id) -- create a swap directly
		THEN
			RAISE EXCEPTION 'Alterações do responsável real devem passar pelo fluxo de aprovação.'
				USING ERRCODE = 'check_violation';
		END IF;
	END IF;

	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_b_enforce_day_protection
	BEFORE INSERT OR UPDATE OR DELETE ON public.care_schedules
	FOR EACH ROW EXECUTE FUNCTION public.enforce_day_protection();

-- Function grants (triggers run as owner; grants kept tidy anyway).
REVOKE ALL ON FUNCTION public.set_care_schedule_family()   FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_swap_request_family()    FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.enforce_profile_protection() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.enforce_day_protection()     FROM PUBLIC, anon;

-- ---------------------------------------------------------------------------
-- 10. Register migration
-- ---------------------------------------------------------------------------

INSERT INTO public.schema_migrations (version, description)
VALUES ('V008', 'families_and_admin')
ON CONFLICT (version) DO NOTHING;

COMMIT;
