-- =============================================================================
-- V009 — Self-service sign-up and family invitations (F-15)
-- Guarda Compartilhada — Supabase/PostgreSQL
--
-- Turns onboarding self-service. Two flows, both atomic:
--
-- 1. FOUNDER  — /register: SignUp carries full_name + role in the user
--    metadata; the handle_new_user trigger (AFTER INSERT ON auth.users)
--    creates the family and the profile (is_admin = true) in one transaction.
-- 2. INVITEE  — /register?invite=<token>: the founder creates an invitation
--    (create_invitation RPC → row in family_invitations, e-mail sent by the
--    app via the send-swap-email Edge Function); SignUp carries the token and
--    the trigger joins the profile to the invitation's family with the
--    invitation's role (is_admin = false), marking the invite accepted.
--
-- Also:
-- 3. get_invite_info(token) — SECURITY DEFINER, callable by anon: minimal
--    data (family/inviter/role/e-mail) to render the invited register page
--    pre-auth. The token itself is the capability; invalid/expired → no row.
-- 4. set_member_admin(profile, flag) — in-app promote/demote (F-14 leftover).
--    RLS only allows own-row profile updates, so this RPC performs the write;
--    the V008 enforce_profile_protection trigger still fires with the CALLER's
--    auth.uid() and keeps every invariant (admin-of-same-family only, last
--    admin cannot be demoted).
-- 5. Hardening: profiles_own_insert (V001) is dropped — profiles are created
--    exclusively by handle_new_user now, so clients need no INSERT path.
--
-- Invitation rules (enforced in create_invitation): caller must be an admin;
-- family must still have fewer than 2 members; the e-mail cannot already have
-- a profile; creating a new invite revokes the previous pending one (resend =
-- revoke + new token). Invitations expire after 7 days.
--
-- Requires the Dashboard setting Authentication → "Confirm email" = ON
-- (e-mail is the workflow notification channel — see supabase/README.md).
-- Apply via the Supabase SQL Editor against the target project AFTER V008.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. family_invitations table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.family_invitations (
	id          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	family_id   bigint                   NOT NULL REFERENCES public.families (id),
	email       text                     NOT NULL,
	role_id     bigint                   NOT NULL REFERENCES public.roles (id),
	token       uuid                     NOT NULL DEFAULT gen_random_uuid(),
	invited_by  bigint                   NOT NULL REFERENCES public.profiles (id),
	created_at  timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	expires_at  timestamp with time zone NOT NULL DEFAULT timezone('utc', now()) + interval '7 days',
	accepted_at timestamp with time zone,
	revoked_at  timestamp with time zone,
	CONSTRAINT family_invitations_pkey      PRIMARY KEY (id),
	CONSTRAINT family_invitations_token_key UNIQUE (token)
);

ALTER TABLE public.family_invitations ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.family_invitations FROM anon;
GRANT  ALL ON public.family_invitations TO authenticated, service_role;
REVOKE ALL ON SEQUENCE public.family_invitations_id_seq FROM anon;
GRANT  ALL ON SEQUENCE public.family_invitations_id_seq TO authenticated, service_role;

-- Members read their family's invitations (status/resend UI). All writes go
-- through the SECURITY DEFINER RPCs below — no client INSERT/UPDATE/DELETE.
CREATE POLICY "family_invitations_family_read"
	ON public.family_invitations FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

-- ---------------------------------------------------------------------------
-- 2. handle_new_user — atomic family/profile creation on sign-up
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	meta_name   text;
	meta_role   text;
	meta_token  text;
	meta_family text;
	inv         public.family_invitations%ROWTYPE;
	fam_id      bigint;
	new_role_id bigint;
	admin_flag  boolean;
BEGIN
	-- Idempotency: never duplicate a profile (e.g. trigger re-run).
	IF EXISTS (SELECT 1 FROM public.profiles WHERE user_id = NEW.id) THEN
		RETURN NEW;
	END IF;

	meta_name   := NULLIF(trim(NEW.raw_user_meta_data ->> 'full_name'), '');
	meta_role   := NULLIF(trim(NEW.raw_user_meta_data ->> 'role'), '');
	meta_token  := NULLIF(trim(NEW.raw_user_meta_data ->> 'invite_token'), '');
	meta_family := NULLIF(trim(NEW.raw_user_meta_data ->> 'family_name'), '');

	-- Fallback: e-mail local part (metadata should always carry the name).
	IF meta_name IS NULL THEN
		meta_name := split_part(NEW.email, '@', 1);
	END IF;

	IF meta_token IS NOT NULL THEN
		-- INVITEE: token must be valid, pending and issued for this e-mail.
		-- (a malformed token must fail with the friendly message, not a cast error)
		BEGIN
			SELECT * INTO inv
			FROM public.family_invitations
			WHERE token = meta_token::uuid
			  AND accepted_at IS NULL
			  AND revoked_at  IS NULL
			  AND expires_at  > timezone('utc', now())
			  AND lower(email) = lower(NEW.email);
		EXCEPTION WHEN invalid_text_representation THEN
			inv := NULL;
		END;

		IF inv.id IS NULL THEN
			RAISE EXCEPTION 'Convite inválido, expirado ou emitido para outro e-mail.'
				USING ERRCODE = 'check_violation';
		END IF;

		-- The family may have completed meanwhile (invite raced a manual add).
		IF (SELECT count(*) FROM public.profiles WHERE family_id = inv.family_id) >= 2 THEN
			RAISE EXCEPTION 'Esta família já possui dois responsáveis cadastrados.'
				USING ERRCODE = 'check_violation';
		END IF;

		fam_id      := inv.family_id;
		new_role_id := inv.role_id;
		admin_flag  := false;

		UPDATE public.family_invitations
		SET accepted_at = timezone('utc', now())
		WHERE id = inv.id;
	ELSE
		-- FOUNDER: creates the family and becomes its admin (F-14 decision).
		IF meta_role IS NULL THEN
			RAISE EXCEPTION 'Selecione o papel (pai ou mãe) para criar a conta.'
				USING ERRCODE = 'check_violation';
		END IF;

		-- Tolerant match: seed data differs across environments — the dev DB
		-- holds 'Pai'/'Mãe' while V001 documents 'father'/'mother'. Accept both
		-- vocabularies (the client always sends the canonical english value).
		SELECT id INTO new_role_id
		FROM public.roles
		WHERE lower(trim(role)) = ANY (
			CASE lower(meta_role)
				WHEN 'father' THEN ARRAY['father', 'pai']
				WHEN 'mother' THEN ARRAY['mother', 'mãe', 'mae']
				ELSE ARRAY[lower(meta_role)]
			END)
		ORDER BY id
		LIMIT 1;
		IF new_role_id IS NULL THEN
			RAISE EXCEPTION 'Papel inválido: %.', meta_role
				USING ERRCODE = 'check_violation';
		END IF;

		-- Family name chosen by the founder; neutral fallback for safety
		-- (the register form makes the field required).
		INSERT INTO public.families (name)
		VALUES (COALESCE(meta_family, 'Família ' || meta_name))
		RETURNING id INTO fam_id;

		admin_flag := true;
	END IF;

	INSERT INTO public.profiles (user_id, full_name, role_id, email, family_id, is_admin)
	VALUES (NEW.id, meta_name, new_role_id, NEW.email, fam_id, admin_flag);

	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
	AFTER INSERT ON auth.users
	FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 3. get_invite_info — pre-auth data for the invited register page
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_invite_info(p_token uuid)
RETURNS TABLE (family_name text, inviter_name text, invited_email text, role_name text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
	SELECT f.name, p.full_name, i.email, r.role
	FROM public.family_invitations i
	JOIN public.families f ON f.id = i.family_id
	JOIN public.profiles p ON p.id = i.invited_by
	JOIN public.roles    r ON r.id = i.role_id
	WHERE i.token = p_token
	  AND i.accepted_at IS NULL
	  AND i.revoked_at  IS NULL
	  AND i.expires_at  > timezone('utc', now());
$$;

-- ---------------------------------------------------------------------------
-- 4. create_invitation / revoke_invitation
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.create_invitation(p_email text, p_role_id bigint)
RETURNS TABLE (invitation_id bigint, token uuid, expires_at timestamp with time zone)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	me  public.profiles%ROWTYPE;
	inv public.family_invitations%ROWTYPE;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	IF me.id IS NULL OR NOT me.is_admin THEN
		RAISE EXCEPTION 'Somente administradores da família podem enviar convites.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF (SELECT count(*) FROM public.profiles WHERE family_id = me.family_id) >= 2 THEN
		RAISE EXCEPTION 'Esta família já possui dois responsáveis cadastrados.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF EXISTS (SELECT 1 FROM public.profiles WHERE lower(email) = lower(trim(p_email))) THEN
		RAISE EXCEPTION 'Este e-mail já possui cadastro no aplicativo.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF NOT EXISTS (SELECT 1 FROM public.roles WHERE id = p_role_id) THEN
		RAISE EXCEPTION 'Papel inválido.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- Resend = revoke the previous pending invite + issue a fresh token.
	UPDATE public.family_invitations
	SET revoked_at = timezone('utc', now())
	WHERE family_id = me.family_id AND accepted_at IS NULL AND revoked_at IS NULL;

	INSERT INTO public.family_invitations (family_id, email, role_id, invited_by)
	VALUES (me.family_id, lower(trim(p_email)), p_role_id, me.id)
	RETURNING * INTO inv;

	RETURN QUERY SELECT inv.id, inv.token, inv.expires_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_invitation(p_invitation_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	me public.profiles%ROWTYPE;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	IF me.id IS NULL OR NOT me.is_admin THEN
		RAISE EXCEPTION 'Somente administradores da família podem revogar convites.'
			USING ERRCODE = 'check_violation';
	END IF;

	UPDATE public.family_invitations
	SET revoked_at = timezone('utc', now())
	WHERE id = p_invitation_id
	  AND family_id = me.family_id
	  AND accepted_at IS NULL
	  AND revoked_at  IS NULL;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. rename_family — family admins can rename their family
-- ---------------------------------------------------------------------------

-- families has no client UPDATE policy (writes go through DEFINER RPCs, like
-- everything else in V009); the founder names the family at sign-up and any
-- family admin can rename it later.
CREATE OR REPLACE FUNCTION public.rename_family(p_name text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	me       public.profiles%ROWTYPE;
	new_name text;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	IF me.id IS NULL OR NOT me.is_admin THEN
		RAISE EXCEPTION 'Somente administradores da família podem renomear a família.'
			USING ERRCODE = 'check_violation';
	END IF;

	new_name := NULLIF(trim(p_name), '');
	IF new_name IS NULL OR length(new_name) > 80 THEN
		RAISE EXCEPTION 'Informe um nome de família com até 80 caracteres.'
			USING ERRCODE = 'check_violation';
	END IF;

	UPDATE public.families SET name = new_name WHERE id = me.family_id;
END;
$$;

-- ---------------------------------------------------------------------------
-- 6. set_member_admin — in-app promote/demote (F-14 deferred item)
-- ---------------------------------------------------------------------------

-- RLS only allows own-row updates on profiles, so this DEFINER RPC carries the
-- write; enforce_profile_protection (V008) still runs with the caller's
-- auth.uid() and enforces admin-of-same-family + the last-admin invariant.
CREATE OR REPLACE FUNCTION public.set_member_admin(p_profile_id bigint, p_is_admin boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	me public.profiles%ROWTYPE;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	IF me.id IS NULL OR NOT me.is_admin THEN
		RAISE EXCEPTION 'Somente administradores da família podem alterar permissões.'
			USING ERRCODE = 'check_violation';
	END IF;

	UPDATE public.profiles
	SET is_admin = p_is_admin
	WHERE id = p_profile_id AND family_id = me.family_id;

	IF NOT FOUND THEN
		RAISE EXCEPTION 'Perfil não encontrado na sua família.'
			USING ERRCODE = 'check_violation';
	END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 7. Resync identity sequences with manually-seeded data
-- ---------------------------------------------------------------------------

-- The original profiles/roles/families rows were inserted with explicit ids
-- (manual seeding), so the identity sequences never advanced — the trigger's
-- first INSERT would collide ("duplicate key ... profiles_pkey"). Setting each
-- sequence to max(id)+1 is safe to run at any time, on any environment.
SELECT setval(pg_get_serial_sequence('public.profiles', 'id'),
	COALESCE((SELECT max(id) FROM public.profiles), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.families', 'id'),
	COALESCE((SELECT max(id) FROM public.families), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('public.roles', 'id'),
	COALESCE((SELECT max(id) FROM public.roles), 0) + 1, false);

-- ---------------------------------------------------------------------------
-- 8. Hardening + grants
-- ---------------------------------------------------------------------------

-- Profiles are now created exclusively by handle_new_user (S-06 spirit).
DROP POLICY IF EXISTS "profiles_own_insert" ON public.profiles;

REVOKE ALL ON FUNCTION public.handle_new_user()                     FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_invite_info(uuid)                 FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_invitation(text, bigint)       FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.revoke_invitation(bigint)             FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rename_family(text)                   FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.set_member_admin(bigint, boolean)     FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.get_invite_info(uuid)             TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.create_invitation(text, bigint)   TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.revoke_invitation(bigint)         TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rename_family(text)               TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_member_admin(bigint, boolean) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 9. Register migration
-- ---------------------------------------------------------------------------

INSERT INTO public.schema_migrations (version, description)
VALUES ('V009', 'signup_and_invitations')
ON CONFLICT (version) DO NOTHING;

COMMIT;
