-- =============================================================================
-- S-11 (PR2) — whole-family deletion with multi-party consent
--
-- Product decisions (July 2026, confirmed at implementation):
--   · Admin-initiated; every OTHER active member may respond within 30 days.
--     SILENCE counts as consent; ANY explicit refusal ends the request at once
--     (the family continues); the REQUESTER may withdraw (sudo) at any time —
--     a new request restarts the 30 days.
--   · The 30-day window ALWAYS runs in full — explicit agreement is recorded
--     for the status panel but never accelerates the purge (the window doubles
--     as the regret grace, mirroring the individual exit). Because agreeing
--     changes nothing destructive, responding needs no sudo; requesting and
--     withdrawing do (S-10).
--   · The app stays usable during the window (persistent banner in the UI);
--     INVITATIONS and INDIVIDUAL EXITS are blocked while a request is pending
--     (one destructive flow at a time). A member already in individual grace
--     MAY still cancel their exit and return — returning makes them active
--     again, which includes the right to refuse the family deletion.
--   · Reminder 3 days before the purge (in-app + e-mail, sent once).
--   · After the window: full purge (history and audit included, art. 16
--     retention satisfied by the window + the F-17 export) via the existing
--     purge_family_data teardown; the cron deletes the GoTrue users and sends
--     a final e-mail to the addresses collected BEFORE the purge.
-- =============================================================================

-- ── 1. Tables ─────────────────────────────────────────────────────────────────

CREATE TABLE public.family_deletion_requests (
	id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	family_id        bigint NOT NULL REFERENCES public.families (id) ON DELETE CASCADE,
	requested_by     bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	requested_at     timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
	scheduled_for    timestamp with time zone NOT NULL,
	status           text NOT NULL DEFAULT 'pending'
	                 CHECK (status IN ('pending', 'refused', 'withdrawn')),
	resolved_at      timestamp with time zone,
	resolved_by      bigint REFERENCES public.profiles (id) ON DELETE SET NULL,
	reminder_sent_at timestamp with time zone
);

-- One live request per family; resolved ones stay as history until the purge.
CREATE UNIQUE INDEX family_deletion_requests_one_pending
	ON public.family_deletion_requests (family_id) WHERE status = 'pending';

CREATE TABLE public.family_deletion_responses (
	id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_id   bigint NOT NULL REFERENCES public.family_deletion_requests (id) ON DELETE CASCADE,
	profile_id   bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	agreed       boolean NOT NULL,
	responded_at timestamp with time zone DEFAULT timezone('utc', now()) NOT NULL,
	UNIQUE (request_id, profile_id)
);

-- Family members read the request/status panel; ALL writes go through the
-- SECURITY DEFINER RPCs below (no INSERT/UPDATE/DELETE policies on purpose).
ALTER TABLE public.family_deletion_requests  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_deletion_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY family_deletion_requests_select ON public.family_deletion_requests
	FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

CREATE POLICY family_deletion_responses_select ON public.family_deletion_responses
	FOR SELECT TO authenticated
	USING (EXISTS (SELECT 1 FROM public.family_deletion_requests r
	               WHERE r.id = request_id AND r.family_id = public.get_my_family_id()));

GRANT SELECT ON public.family_deletion_requests  TO authenticated;
GRANT SELECT ON public.family_deletion_responses TO authenticated;
GRANT ALL    ON public.family_deletion_requests  TO service_role;
GRANT ALL    ON public.family_deletion_responses TO service_role;

-- ── 2. request_family_deletion — admin + sudo ────────────────────────────────

CREATE OR REPLACE FUNCTION public.request_family_deletion()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me       public.profiles%ROWTYPE;
	deadline timestamp with time zone := timezone('utc', now()) + interval '30 days';
	deadline_br text;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();
	IF me.id IS NULL OR me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Perfil não encontrado ou em processo de saída.' USING ERRCODE = 'check_violation';
	END IF;
	IF NOT me.is_admin THEN
		RAISE EXCEPTION 'Somente administradores podem solicitar a exclusão da família.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- S-10: sensitive operation — requires a fresh password confirmation.
	IF NOT public.is_elevated() THEN
		RAISE EXCEPTION 'ELEVATION_REQUIRED: Confirme sua senha para solicitar a exclusão da família.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	-- The consent flow only makes sense with other members to consult; the
	-- last active member deletes the family through their own exit (PR1).
	IF public.active_member_count(me.family_id) <= 1 THEN
		RAISE EXCEPTION 'Você é o único responsável ativo — a exclusão da família acontece pela sua própria saída, em "Sair da família".'
			USING ERRCODE = 'check_violation';
	END IF;

	IF EXISTS (SELECT 1 FROM public.family_deletion_requests
	           WHERE family_id = me.family_id AND status = 'pending') THEN
		RAISE EXCEPTION 'Já existe uma solicitação de exclusão da família em andamento.'
			USING ERRCODE = 'check_violation';
	END IF;

	INSERT INTO public.family_deletion_requests (family_id, requested_by, scheduled_for)
	VALUES (me.family_id, me.id, deadline);

	INSERT INTO public.account_logs (family_id, actor_profile_id, action, new_value)
	VALUES (me.family_id, me.id, 'family_deletion_requested', to_char(deadline, 'YYYY-MM-DD'));

	deadline_br := to_char(deadline AT TIME ZONE 'America/Sao_Paulo', 'DD/MM/YYYY');

	-- Confirmation to the requester.
	INSERT INTO public.notifications (recipient_profile_id, type, title, message)
	VALUES (me.id, 'family_deletion',
	        'Exclusão da família solicitada',
	        'Você solicitou a exclusão da família. Se ninguém recusar até ' || deadline_br ||
	        ', todos os dados (calendário, histórico e contas) serão apagados definitivamente. ' ||
	        'Você pode retirar a solicitação a qualquer momento.');

	-- Heads-up to every other active member: silence = consent, refusal ends it.
	INSERT INTO public.notifications (recipient_profile_id, type, title, message)
	SELECT p.id, 'family_deletion',
	       'Exclusão da família solicitada',
	       me.full_name || ' solicitou a exclusão da família. Se ninguém recusar até ' || deadline_br ||
	       ', TODOS os dados (calendário, histórico e contas de todos) serão apagados definitivamente. ' ||
	       'Você pode recusar em Perfil > Exclusão da família — qualquer recusa cancela a exclusão.'
	FROM public.profiles p
	WHERE p.family_id = me.family_id AND p.left_at IS NULL AND p.user_id IS NOT NULL AND p.id <> me.id;
END;
$$;

ALTER FUNCTION public.request_family_deletion() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.request_family_deletion() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.request_family_deletion() FROM anon;
GRANT EXECUTE ON FUNCTION public.request_family_deletion() TO authenticated, service_role;

-- ── 3. respond_family_deletion — any other active member; refusal ends it ────

CREATE OR REPLACE FUNCTION public.respond_family_deletion(p_agree boolean)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me  public.profiles%ROWTYPE;
	req public.family_deletion_requests%ROWTYPE;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();
	IF me.id IS NULL OR me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Perfil não encontrado ou em processo de saída.' USING ERRCODE = 'check_violation';
	END IF;

	SELECT * INTO req FROM public.family_deletion_requests
	WHERE family_id = me.family_id AND status = 'pending';
	IF req.id IS NULL THEN
		RAISE EXCEPTION 'Não há solicitação de exclusão da família pendente.'
			USING ERRCODE = 'check_violation';
	END IF;
	IF req.requested_by = me.id THEN
		RAISE EXCEPTION 'Quem solicitou a exclusão pode apenas retirar a solicitação.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- Recorded for the status panel; a member may change their answer while
	-- the request is pending (agree → refuse included — refusal always wins).
	INSERT INTO public.family_deletion_responses (request_id, profile_id, agreed)
	VALUES (req.id, me.id, p_agree)
	ON CONFLICT (request_id, profile_id)
	DO UPDATE SET agreed = EXCLUDED.agreed, responded_at = timezone('utc', now());

	IF p_agree THEN
		INSERT INTO public.account_logs (family_id, actor_profile_id, action)
		VALUES (me.family_id, me.id, 'family_deletion_agreed');

		INSERT INTO public.notifications (recipient_profile_id, type, title, message)
		VALUES (req.requested_by, 'family_deletion',
		        'Resposta à exclusão da família',
		        me.full_name || ' concordou com a exclusão da família.');
	ELSE
		UPDATE public.family_deletion_requests
		SET status = 'refused', resolved_at = timezone('utc', now()), resolved_by = me.id
		WHERE id = req.id;

		INSERT INTO public.account_logs (family_id, actor_profile_id, action)
		VALUES (me.family_id, me.id, 'family_deletion_refused');

		-- Everyone (requester included) learns the family continues.
		INSERT INTO public.notifications (recipient_profile_id, type, title, message)
		SELECT p.id, 'family_deletion',
		       'Exclusão da família cancelada',
		       me.full_name || ' recusou a exclusão da família. A solicitação foi encerrada e a família continua.'
		FROM public.profiles p
		WHERE p.family_id = me.family_id AND p.left_at IS NULL AND p.user_id IS NOT NULL;
	END IF;
END;
$$;

ALTER FUNCTION public.respond_family_deletion(boolean) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.respond_family_deletion(boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.respond_family_deletion(boolean) FROM anon;
GRANT EXECUTE ON FUNCTION public.respond_family_deletion(boolean) TO authenticated, service_role;

-- ── 4. withdraw_family_deletion — requester only, sudo ───────────────────────

CREATE OR REPLACE FUNCTION public.withdraw_family_deletion()
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me  public.profiles%ROWTYPE;
	req public.family_deletion_requests%ROWTYPE;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();
	IF me.id IS NULL THEN
		RAISE EXCEPTION 'Perfil não encontrado.' USING ERRCODE = 'check_violation';
	END IF;

	SELECT * INTO req FROM public.family_deletion_requests
	WHERE family_id = me.family_id AND status = 'pending';
	IF req.id IS NULL THEN
		RAISE EXCEPTION 'Não há solicitação de exclusão da família pendente.'
			USING ERRCODE = 'check_violation';
	END IF;
	IF req.requested_by <> me.id THEN
		RAISE EXCEPTION 'Somente quem solicitou a exclusão pode retirá-la.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF NOT public.is_elevated() THEN
		RAISE EXCEPTION 'ELEVATION_REQUIRED: Confirme sua senha para retirar a solicitação.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	UPDATE public.family_deletion_requests
	SET status = 'withdrawn', resolved_at = timezone('utc', now()), resolved_by = me.id
	WHERE id = req.id;

	INSERT INTO public.account_logs (family_id, actor_profile_id, action)
	VALUES (me.family_id, me.id, 'family_deletion_withdrawn');

	INSERT INTO public.notifications (recipient_profile_id, type, title, message)
	SELECT p.id, 'family_deletion',
	       'Exclusão da família retirada',
	       me.full_name || ' retirou a solicitação de exclusão da família. A família continua normalmente.'
	FROM public.profiles p
	WHERE p.family_id = me.family_id AND p.left_at IS NULL AND p.user_id IS NOT NULL;
END;
$$;

ALTER FUNCTION public.withdraw_family_deletion() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.withdraw_family_deletion() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.withdraw_family_deletion() FROM anon;
GRANT EXECUTE ON FUNCTION public.withdraw_family_deletion() TO authenticated, service_role;

-- ── 5. family_deletion_reminders_due — cron helper (D-3, sent once) ──────────
-- Marks the reminder as sent, writes the in-app notices, and hands the request
-- back so the cron dispatches the e-mail twin (send-account-email).

CREATE OR REPLACE FUNCTION public.family_deletion_reminders_due()
RETURNS TABLE (request_id bigint, requester_profile_id bigint)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	r record;
BEGIN
	FOR r IN
		SELECT * FROM public.family_deletion_requests
		WHERE status = 'pending'
		  AND reminder_sent_at IS NULL
		  AND scheduled_for - interval '3 days' <= timezone('utc', now())
		  AND scheduled_for > timezone('utc', now())
	LOOP
		UPDATE public.family_deletion_requests
		SET reminder_sent_at = timezone('utc', now())
		WHERE id = r.id;

		INSERT INTO public.notifications (recipient_profile_id, type, title, message)
		SELECT p.id, 'family_deletion',
		       'Exclusão da família se aproxima',
		       'A família será excluída definitivamente em ' ||
		       to_char(r.scheduled_for AT TIME ZONE 'America/Sao_Paulo', 'DD/MM/YYYY') ||
		       '. Você ainda pode recusar em Perfil > Exclusão da família, ou exportar seus dados antes.'
		FROM public.profiles p
		WHERE p.family_id = r.family_id AND p.left_at IS NULL AND p.user_id IS NOT NULL;

		request_id := r.id;
		requester_profile_id := r.requested_by;
		RETURN NEXT;
	END LOOP;
END;
$$;

ALTER FUNCTION public.family_deletion_reminders_due() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.family_deletion_reminders_due() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.family_deletion_reminders_due() FROM anon;
REVOKE ALL ON FUNCTION public.family_deletion_reminders_due() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.family_deletion_reminders_due() TO service_role;

-- ── 6. purge_expired_family_deletions — cron helper (the purge itself) ───────
-- Collects the farewell data (auth uid + real e-mail + family name) BEFORE the
-- teardown, then reuses purge_family_data. Tombstoned members are naturally
-- excluded (user_id already NULL, e-mail scrubbed); in-grace members are
-- included — their accounts also go. The request rows vanish with the family
-- via the ON DELETE CASCADE foreign keys.

CREATE OR REPLACE FUNCTION public.purge_expired_family_deletions()
RETURNS TABLE (purged_family_id bigint, auth_uid uuid, member_email text, family_name text)
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	r record;
BEGIN
	FOR r IN
		SELECT fdr.id, fdr.family_id
		FROM public.family_deletion_requests fdr
		WHERE fdr.status = 'pending'
		  AND fdr.scheduled_for <= timezone('utc', now())
	LOOP
		RETURN QUERY
		SELECT p.family_id, p.user_id, p.email, f.name
		FROM public.profiles p
		JOIN public.families f ON f.id = p.family_id
		WHERE p.family_id = r.family_id AND p.user_id IS NOT NULL;

		PERFORM * FROM public.purge_family_data(r.family_id);
	END LOOP;
END;
$$;

ALTER FUNCTION public.purge_expired_family_deletions() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.purge_expired_family_deletions() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_expired_family_deletions() FROM anon;
REVOKE ALL ON FUNCTION public.purge_expired_family_deletions() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.purge_expired_family_deletions() TO service_role;

-- ── 7. Guard: invitations blocked while a family deletion is pending ─────────
-- Body copied VERBATIM from 20260719120000; only the pending-deletion guard
-- (right after the admin check) is new.

CREATE OR REPLACE FUNCTION public.create_invitation(p_email text, p_role_id bigint)
RETURNS TABLE (invitation_id bigint, token uuid, expires_at timestamp with time zone)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	me        public.profiles%ROWTYPE;
	inv       public.family_invitations%ROWTYPE;
	max_seats constant int := 4;
	taken     int;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();

	IF me.id IS NULL OR NOT me.is_admin THEN
		RAISE EXCEPTION 'Somente administradores da família podem enviar convites.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF EXISTS (SELECT 1 FROM public.family_deletion_requests
	           WHERE family_id = me.family_id AND status = 'pending') THEN
		RAISE EXCEPTION 'Há uma solicitação de exclusão da família em andamento — convites ficam bloqueados até ela ser resolvida.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF EXISTS (SELECT 1 FROM public.profiles
	           WHERE lower(email) = lower(trim(p_email))
	             AND user_id IS NOT NULL AND left_at IS NULL) THEN
		RAISE EXCEPTION 'Este e-mail já possui cadastro no aplicativo.'
			USING ERRCODE = 'check_violation';
	END IF;

	IF NOT EXISTS (SELECT 1 FROM public.roles WHERE id = p_role_id) THEN
		RAISE EXCEPTION 'Papel inválido.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- Resend semantics: revoke this e-mail's previous open invitation BEFORE
	-- counting seats, so a resend never trips the cap it already occupies.
	UPDATE public.family_invitations
	SET revoked_at = timezone('utc', now())
	WHERE family_id = me.family_id
	  AND lower(email) = lower(trim(p_email))
	  AND accepted_at IS NULL AND revoked_at IS NULL;

	-- Seats taken = ACTIVE members + open (pending, unexpired) invitations.
	SELECT public.active_member_count(me.family_id)
	     + (SELECT count(*) FROM public.family_invitations fi
	        WHERE fi.family_id = me.family_id
	          AND fi.accepted_at IS NULL AND fi.revoked_at IS NULL
	          AND fi.expires_at > timezone('utc', now()))
	INTO taken;

	IF taken >= max_seats THEN
		RAISE EXCEPTION 'Esta família já atingiu o limite de % responsáveis (contando convites pendentes).', max_seats
			USING ERRCODE = 'check_violation';
	END IF;

	INSERT INTO public.family_invitations (family_id, email, role_id, invited_by)
	VALUES (me.family_id, lower(trim(p_email)), p_role_id, me.id)
	RETURNING * INTO inv;

	RETURN QUERY SELECT inv.id, inv.token, inv.expires_at;
END;
$$;

-- ── 8. Guard: individual exit blocked while a family deletion is pending ─────
-- Body copied VERBATIM from 20260720190000; only the pending-deletion guard
-- (right after the left_at check) is new. Cancelling an exit stays ALLOWED —
-- a returning member becomes active again and may refuse the family deletion.

CREATE OR REPLACE FUNCTION public.request_account_deletion(p_new_admin_id bigint DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
	me              public.profiles%ROWTYPE;
	today           date := (now() AT TIME ZONE 'America/Sao_Paulo')::date;
	other_active    int;
	has_other_admin boolean;
	is_last         boolean;
	sr              record;
BEGIN
	SELECT * INTO me FROM public.profiles WHERE user_id = auth.uid();
	IF me.id IS NULL THEN
		RAISE EXCEPTION 'Perfil não encontrado.' USING ERRCODE = 'check_violation';
	END IF;
	IF me.left_at IS NOT NULL THEN
		RAISE EXCEPTION 'Sua saída já foi solicitada.' USING ERRCODE = 'check_violation';
	END IF;

	IF EXISTS (SELECT 1 FROM public.family_deletion_requests
	           WHERE family_id = me.family_id AND status = 'pending') THEN
		RAISE EXCEPTION 'Há uma solicitação de exclusão da família em andamento — a saída individual fica bloqueada até ela ser resolvida.'
			USING ERRCODE = 'check_violation';
	END IF;

	-- S-10: sensitive operation — requires a fresh password confirmation.
	IF NOT public.is_elevated() THEN
		RAISE EXCEPTION 'ELEVATION_REQUIRED: Confirme sua senha para sair da família.'
			USING ERRCODE = 'insufficient_privilege';
	END IF;

	other_active := public.active_member_count(me.family_id) - 1;
	is_last := (other_active <= 0);

	IF NOT is_last THEN
		-- Members remain: keep the >= 1 admin invariant. If I am the only admin,
		-- a successor must be named and is promoted BEFORE I leave (promotion is
		-- audited normally, so it happens before the deletion-context bypass).
		has_other_admin := EXISTS (
			SELECT 1 FROM public.profiles
			WHERE family_id = me.family_id AND is_admin AND left_at IS NULL
			  AND user_id IS NOT NULL AND id <> me.id);

		IF me.is_admin AND NOT has_other_admin THEN
			IF p_new_admin_id IS NULL THEN
				RAISE EXCEPTION 'Indique um novo administrador para assumir antes de sair.'
					USING ERRCODE = 'check_violation';
			END IF;
			IF NOT EXISTS (
				SELECT 1 FROM public.profiles
				WHERE id = p_new_admin_id AND family_id = me.family_id
				  AND left_at IS NULL AND user_id IS NOT NULL AND id <> me.id) THEN
				RAISE EXCEPTION 'Selecione um responsável ativo da família para assumir como administrador.'
					USING ERRCODE = 'check_violation';
			END IF;
			UPDATE public.profiles SET is_admin = true WHERE id = p_new_admin_id;
		END IF;
	END IF;

	PERFORM set_config('app.deletion_context', 'on', true);

	-- Cancel my pending swap requests and notify the counterpart.
	FOR sr IN
		SELECT * FROM public.swap_requests
		WHERE family_id = me.family_id
		  AND status IN ('pending', 'revert_pending')
		  AND (requesting_profile_id = me.id OR target_profile_id = me.id
		       OR proposed_actual_parent_id = me.id OR previous_actual_parent_id = me.id)
	LOOP
		UPDATE public.swap_requests
		SET status = 'cancelled', resolved_at = timezone('utc', now()), resolved_by = 'system'
		WHERE id = sr.id;

		INSERT INTO public.notifications (recipient_profile_id, type, title, message, swap_request_id)
		SELECT p.id, 'swap_cancelled',
		       'Solicitação cancelada',
		       me.full_name || ' saiu da família e a solicitação de troca de ' ||
		           to_char(sr.schedule_date, 'DD/MM/YYYY') || ' foi cancelada.',
		       sr.id
		FROM public.profiles p
		WHERE p.family_id = me.family_id AND p.left_at IS NULL AND p.user_id IS NOT NULL
		  AND p.id IN (sr.requesting_profile_id, sr.target_profile_id) AND p.id <> me.id;
	END LOOP;

	-- Clear my FUTURE days — TODAY included (product decision: the current day
	-- counts as future for a departed member, even past its handoff time).
	UPDATE public.care_schedules
	SET actual_parent_id = NULL, updated_at = timezone('utc', now())
	WHERE family_id = me.family_id AND schedule_date >= today
	  AND actual_parent_id = me.id AND scheduled_parent_id <> me.id;

	DELETE FROM public.care_schedules
	WHERE family_id = me.family_id AND schedule_date >= today
	  AND scheduled_parent_id = me.id;

	-- Enter the leaving state (seat frees immediately; the GoTrue user survives
	-- so I can still cancel). When I am the last member, the cron will purge the
	-- whole family once the grace elapses.
	UPDATE public.profiles
	SET left_at = timezone('utc', now()),
	    deletion_scheduled_for = timezone('utc', now()) + interval '30 days'
	WHERE id = me.id;

	INSERT INTO public.account_logs (family_id, actor_profile_id, target_profile_id, action)
	VALUES (me.family_id, me.id, me.id, 'account_deletion_requested');

	-- Confirmation to myself (text differs for the last-member family removal).
	INSERT INTO public.notifications (recipient_profile_id, type, title, message)
	VALUES (me.id, 'account_deletion',
	        CASE WHEN is_last THEN 'Exclusão da família solicitada' ELSE 'Saída solicitada' END,
	        CASE WHEN is_last
	             THEN 'Como você é o único responsável, sua saída removerá a família e todos os dados após 30 dias. Você pode cancelar nesse período.'
	             ELSE 'Sua saída da família foi solicitada. Você tem 30 dias para cancelar; após esse prazo a conta será apagada.' END);

	-- Heads-up to the other active members (only when the family stays).
	IF NOT is_last THEN
		INSERT INTO public.notifications (recipient_profile_id, type, title, message)
		SELECT p.id, 'account_deletion',
		       'Um responsável saiu',
		       me.full_name || ' saiu da família. Os dias futuros dessa pessoa foram liberados — '
		           || 'verifique o calendário e reatribua o que for necessário.'
		FROM public.profiles p
		WHERE p.family_id = me.family_id AND p.left_at IS NULL AND p.user_id IS NOT NULL AND p.id <> me.id;
	END IF;
END;
$$;
