-- =============================================================================
-- T-39 (PR1) — Billing bookkeeping: subscriptions + webhook event ledger
--
-- Server side of the paid subscription (gateway: Asaas, decided July 2026 —
-- native recurring Pix at BR-friendly fees; hosted/redirect checkout). This
-- migration is bookkeeping + configuration only; the money flow lives in the
-- Edge Functions (`billing-webhook` here in PR1, `billing-checkout` in PR2).
--
-- Product decisions (locked July 2026):
--   · Price: R$ 14,90/month · R$ 149/year (≈2 months free) — per FAMILY, one
--     payer, never per seat. Values live in app_settings (public rows) so the
--     UI mirrors them without a deploy; the CHECKOUT reads the same rows
--     server-side (single source of truth).
--   · Entitlement stays exactly F-32: the webhook flips `families.plan` via
--     set_family_plan (service_role only). Nothing here re-implements it.
--   · Downgrade NEVER deletes data (backlog invariant): premium features go
--     read-only via the existing gates; PR3 adds the grace-period cron
--     (billing.grace_days, default 7) that does the actual overdue downgrade.
--
-- SECURITY MODEL:
--   · `subscriptions`: family members may SELECT their own family's row (the
--     UI shows plan/renewal state); ALL writes are service_role only (no
--     authenticated write policy exists — the webhook/checkout functions write
--     with the service key).
--   · `billing_events`: service_role only, both ways. It is the idempotency
--     ledger and raw-payload audit of everything the gateway ever told us —
--     clients have no business reading gateway payloads (they may contain
--     payer metadata).
--   · `event_id` UNIQUE is the idempotency key: the webhook INSERTs first
--     (ON CONFLICT DO NOTHING) and only applies effects when the row was new,
--     so Asaas redeliveries are no-ops.
-- =============================================================================

-- ── 1. subscriptions — one per family ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.subscriptions (
	id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	family_id                bigint NOT NULL UNIQUE
	                         REFERENCES public.families (id) ON DELETE CASCADE,
	gateway                  text NOT NULL DEFAULT 'asaas' CHECK (gateway IN ('asaas')),
	external_customer_id     text,
	external_subscription_id text UNIQUE,
	status                   text NOT NULL DEFAULT 'pending'
	                         CHECK (status IN ('pending', 'active', 'overdue', 'canceled')),
	cycle                    text NOT NULL CHECK (cycle IN ('monthly', 'annual')),
	price_cents              integer NOT NULL CHECK (price_cents > 0),
	current_period_end       timestamp with time zone,
	overdue_since            timestamp with time zone,
	canceled_at              timestamp with time zone,
	created_at               timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	updated_at               timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Members see their own family's subscription (status/renewal in the UI).
CREATE POLICY subscriptions_select ON public.subscriptions
	FOR SELECT TO authenticated
	USING (family_id = public.get_my_family_id());

GRANT SELECT ON public.subscriptions TO authenticated;
GRANT ALL    ON public.subscriptions TO service_role;

-- ── 2. billing_events — idempotency ledger + raw audit ───────────────────────

CREATE TABLE IF NOT EXISTS public.billing_events (
	id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_id        text NOT NULL UNIQUE,          -- gateway event id (idempotency key)
	event_type      text NOT NULL,                 -- e.g. PAYMENT_CONFIRMED
	subscription_id bigint REFERENCES public.subscriptions (id) ON DELETE SET NULL,
	family_id       bigint,                        -- denormalized; survives subscription deletion
	payload         jsonb NOT NULL,
	received_at     timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.billing_events ENABLE ROW LEVEL SECURITY;
-- No authenticated policy on purpose: service_role only, both directions.
GRANT ALL ON public.billing_events TO service_role;

CREATE INDEX IF NOT EXISTS billing_events_family_idx
	ON public.billing_events (family_id, received_at DESC);

-- ── 3. Billing configuration (T-41 app_settings) ─────────────────────────────
-- Public rows: the Premium page shows price/state without a deploy; the real
-- charge amount is read server-side from these same rows by billing-checkout.
-- grace_days stays non-public (server-only dunning parameter, PR3).

INSERT INTO public.app_settings (key, value, value_type, category, description, is_public) VALUES
	('billing.enabled',             'false', 'bool', 'billing', 'Master switch: when false the app shows the waitlist CTA instead of checkout; the checkout function refuses to create subscriptions.', true),
	('billing.price_monthly_cents', '1490',  'int',  'billing', 'Premium monthly price in BRL cents (per family).', true),
	('billing.price_annual_cents',  '14900', 'int',  'billing', 'Premium annual price in BRL cents (per family, ~2 months free).', true),
	('billing.grace_days',          '7',     'int',  'billing', 'Days of grace after a renewal goes overdue before the plan downgrades to free (PR3 cron).', false)
ON CONFLICT (key) DO NOTHING;
