-- =============================================================================
-- F-09 — push notifications, part 1: the device registry and the dispatcher
--        that hangs off the single writer.
--
-- THE SHAPE. Every push-worthy moment in this product already writes a
-- `notifications` row — some from SQL triggers here, some from the client's own
-- insert in SwapRequestService. Firing push from THAT insert is what keeps the
-- three channels (push, in-app, e-mail) from ever telling different stories:
-- one event, written once, rendered three ways. It also means a future writer
-- gets push for free, with nothing to remember.
--
-- WHAT PUSHES. Ten types, and the rule behind the list is "push only what the
-- recipient did NOT just do": a receipt for your own action (`swap_sent`,
-- `swap_approved_self`, …) reaches a person holding the phone that produced it.
-- The authoritative copy of the list lives in `_shared/push.ts`, which refuses a
-- second time; this filter exists so the vast majority of inserts never pay for
-- an HTTP call at all. `push_notification_mirror_test.dart` keeps the two lists
-- identical.
--
-- SELF-DISARMING. The trigger needs two Vault secrets (`secret_key` and
-- `functions_base_url`). Until the owner creates them — Firebase console work,
-- runbook § 11 — every branch here returns without doing anything, so this
-- migration applies cleanly to a project that will never push and to one that
-- is about to. Same posture as `deploy-web` while the Cloudflare secrets are
-- absent.
--
-- ASYNC BY CONSTRUCTION. pg_net queues the request and returns immediately, so
-- a slow or dead Edge Function can never delay — let alone roll back — the
-- notification INSERT that triggered it. A push that fails is a push that did
-- not happen; the row and its e-mail are untouched.
-- =============================================================================

-- ── 1. The device registry ───────────────────────────────────────────────────
-- One row per (profile, device). The token is the FCM registration token, which
-- rotates on its own schedule — hence UNIQUE on the token and not on the pair:
-- a rotated token arrives as a new row, and the old one dies the next time FCM
-- answers UNREGISTERED to a real send (the only garbage collection there is,
-- because FCM is the only authority on which tokens are dead).

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
	id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	profile_id   bigint NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
	token        text   NOT NULL UNIQUE,
	platform     text   NOT NULL CHECK (platform IN ('android', 'ios', 'web')),
	device_label text,
	created_at   timestamp with time zone NOT NULL DEFAULT timezone('utc', now()),
	last_seen_at timestamp with time zone NOT NULL DEFAULT timezone('utc', now())
);

COMMENT ON TABLE public.push_subscriptions IS
	'F-09: FCM registration tokens, one row per device. Written by the app for its OWN profile; read by send-push-notification. Rows die by UNREGISTERED from FCM or with the profile.';

CREATE INDEX IF NOT EXISTS push_subscriptions_profile_idx
	ON public.push_subscriptions (profile_id);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.push_subscriptions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.push_subscriptions TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.push_subscriptions_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.push_subscriptions_id_seq TO service_role;

-- OWN ROWS ONLY — and deliberately NOT family-scoped, unlike almost everything
-- else here. A caregiver has no business reading, moving or deleting the other
-- parent's device tokens: a token is a capability to interrupt that person's
-- phone, and family membership is not consent to hold it.

DROP POLICY IF EXISTS push_subscriptions_select_own ON public.push_subscriptions;
CREATE POLICY push_subscriptions_select_own ON public.push_subscriptions
	FOR SELECT TO authenticated
	USING (profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS push_subscriptions_insert_own ON public.push_subscriptions;
CREATE POLICY push_subscriptions_insert_own ON public.push_subscriptions
	FOR INSERT TO authenticated
	WITH CHECK (profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS push_subscriptions_update_own ON public.push_subscriptions;
CREATE POLICY push_subscriptions_update_own ON public.push_subscriptions
	FOR UPDATE TO authenticated
	USING (profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid()))
	WITH CHECK (profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS push_subscriptions_delete_own ON public.push_subscriptions;
CREATE POLICY push_subscriptions_delete_own ON public.push_subscriptions
	FOR DELETE TO authenticated
	USING (profile_id = (SELECT id FROM public.profiles WHERE user_id = auth.uid()));

-- ── 2. The dispatcher trigger ────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.dispatch_push_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'extensions', 'vault'
AS $$
DECLARE
	base_url text;
	api_key  text;
BEGIN
	-- The cheap filter. Most inserts (receipts, family fan-out, membership,
	-- quota, billing) stop on this line and never touch pg_net.
	IF NEW.type NOT IN (
		'auto_reminder', 'auto_approved',
		'swap_requested', 'swap_approved', 'swap_rejected', 'swap_cancelled',
		'revert_requested', 'revert_approved', 'revert_rejected', 'revert_cancelled'
	) THEN
		RETURN NULL;
	END IF;

	-- A row written before U-13 (or by a writer that forgot `params`) carries no
	-- render data, and the function would only drop it. Save the round trip.
	IF NEW.params IS NULL THEN
		RETURN NULL;
	END IF;

	SELECT decrypted_secret INTO base_url
	FROM vault.decrypted_secrets WHERE name = 'functions_base_url';

	SELECT decrypted_secret INTO api_key
	FROM vault.decrypted_secrets WHERE name = 'secret_key';

	-- Unarmed project: no Vault secrets, no push, no noise. This is the state of
	-- every environment until the runbook's § 11 is done.
	IF base_url IS NULL OR api_key IS NULL THEN
		RETURN NULL;
	END IF;

	-- S-16: the key goes on `apikey`, NEVER on Authorization — the new-model
	-- secret keys are not JWTs and the platform rejects them there.
	PERFORM net.http_post(
		url     := base_url || '/send-push-notification',
		headers := jsonb_build_object(
			'Content-Type', 'application/json',
			'apikey', api_key),
		body    := jsonb_build_object('notification_id', NEW.id),
		-- 30s, per the runbook's own cron rule: a cold isolate has taken over
		-- five seconds to boot (the send-auth-email incident), and a timeout
		-- here ABORTS the request — it would drop the push and log a failure
		-- for a function that was about to work. Nothing waits on this call.
		timeout_milliseconds := 30000
	);

	RETURN NULL;
EXCEPTION WHEN OTHERS THEN
	-- A push is never worth failing the write that earned it. The notification
	-- row, the badge and the e-mail all stand; only the interruption is lost.
	RAISE WARNING 'dispatch_push_notification failed for notification %: %', NEW.id, SQLERRM;
	RETURN NULL;
END;
$$;

ALTER FUNCTION public.dispatch_push_notification() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.dispatch_push_notification() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS notifications_dispatch_push ON public.notifications;
CREATE TRIGGER notifications_dispatch_push
	AFTER INSERT ON public.notifications
	FOR EACH ROW
	EXECUTE FUNCTION public.dispatch_push_notification();
